# Generated by Django 4.1.7 on 2023-03-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_evento', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('max_boletos', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_boleto', models.CharField(max_length=10)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('hora_compra', models.TimeField(auto_now_add=True)),
                ('comprador', models.CharField(max_length=200)),
                ('status_canjeo', models.BooleanField(default=False)),
                ('status_active', models.BooleanField(default=False)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
    ]
