# Generated by Django 4.1.7 on 2023-03-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True),
        ),
    ]
